- hosts: '{{ test_namespace }}:&tag_TestRole_subject'
  become: true
  roles:
    - role: fluentbit
      action: reset
    - role: fluentd
      action: stop
    - role: logstash
      action: reset
    - role: vector
      action: reset
