---
- name: Ensure Python <= 2.6 bindings for docker are not installed
  pip:
    name:
      - docker-py
    state: absent

- name: Ensure modern Python bindings for docker are installed
  pip:
    name:
      - docker
    state: present
