---
- include_role:
    name: golang

- name: Setup the tcp_test_server user
  user:
    name: tcp_test_server
    createhome: no
    home: /opt/tcp_test_server
    shell: /usr/sbin/nologin

- name: Install tcp_test_server
  shell: /usr/local/go/bin/go get -u github.com/timberio/tcp_test_server
  environment:
    GOPATH: /home/{{ ansible_user }}/go

- name: Build the tcp_test_server binary
  shell:
    cmd: /usr/local/go/bin/go build
    chdir: /home/{{ ansible_user }}/go/src/github.com/timberio/tcp_test_server
  environment:
    GOPATH: /home/{{ ansible_user }}/go

- name: Install the tcp_test_server binary
  shell:
    cmd: mv tcp_test_server /usr/local/bin
    chdir: /home/{{ ansible_user }}/go/src/github.com/timberio/tcp_test_server