- hosts: '{{ test_namespace }}:&tag_TestRole_subject'
  become: true
  roles:
    - role: fluentbit
      action: reset
    - role: fluentd
      action: stop
    - role: logstash
      action: reset
    - role: splunk_heavy_forwarder
      action: reset
    - role: splunk_universal_forwarder
      action: reset
    - role: vector
      action: reset

- hosts: '{{ test_namespace }}:&tag_TestRole_consumer'
  become: true
  roles:
    - role: tcp_test_server
      action: stop
