---
- name: Setup the td-agent-bit user
  user:
    name: td-agent-bit
    createhome: no
    home: /opt/td-agent-bit
    shell: /usr/sbin/nologin

- name: Create the /etc/td-agent-bit directory
  file:
    path: /etc/td-agent-bit
    state: directory

- name: Create the /var/lib/td-agent-bit directory
  file:
    path: /var/lib/td-agent-bit
    state: directory
    owner: td-agent-bit
    group: td-agent-bit
    mode: 0700

- name: Add td-agent-bit apt-key
  apt_key:
    url: https://packages.fluentbit.io/fluentbit.key
    state: present

- name: Add td-agent-bit apt repository
  apt_repository:
    repo: 'deb https://packages.fluentbit.io/debian/stretch stretch main'
    state: present
    filename: td-agent-bit
    update_cache: yes

- name: Install td-agent-bit
  apt:
    name: td-agent-bit={{ version }}
    state: present

- name: Remove parsers.conf
  file:
    path: /etc/td-agent-bit/parsers.conf
    state: absent

- name: Install td-agent-bit daemon systemd script
  copy:
    src: td-agent-bit.service
    dest: /etc/systemd/system/td-agent-bit.service
    mode: 0644
    remote_src: no

# This ensures that the process is not running. Each test is responsible
# for starting and stopping the relevant services.
- name: Ensure the td-agent-bit service is stopped
  systemd:
    name: td-agent-bit
    daemon_reload: yes
    enabled: no
    state: stopped
