[sources.in]
  type    = "tcp"
  address = "127.0.0.1:{{ subject_port }}"

[sinks.out]
  inputs  = ["in"]
  type    = "tcp"
  address = "{{ consumer_instance.ec2_private_ip_address }}:{{ consumer_port }}"