---
- name: Stop dstat
  command:
    argv:
      - pkill
      - -f
      - dstat

- include_role:
    name: subjects
  vars:
    action: load_facts

- name: Upload dstat CSV to S3
  command:
    argv:
      - aws
      - s3
      - cp
      - /tmp/dstat.csv
      - '{{ profiling_results_s3_url }}'
      - --acl
      - bucket-owner-full-control
