---
- name: Stop dstat
  # We use command instead of shell because shell returns a non zero exit code
  # which fails this step.
  command: pkill -f "dstat"

- name: Upload dstat CSV to S3
  command:
    argv:
      - aws
      - s3
      - cp
      - /tmp/dstat.csv
      - '{{ profiling_results_s3_url }}'
