---
- include_role:
    name: file_test_server
  vars:
    action: install

- include_role:
    name: http_test_server
  vars:
    action: install
    server_address: "{{ http_server_address }}"

- include_role:
    name: tcp_test_server
  vars:
    action: install
    server_address: "{{ tcp_server_address }}"