---
- name: "Sending data to {{ address }} for {{ timeout }} seconds"
  shell: |
    timeout {{ timeout }} bash -c "
      while true
      do
        cat {{ file }} | \
        socat -u - {{ address }};
      done
    "
  register: timeout
  failed_when: timeout.rc != 124
