---
- name: Ensure old docker versions are not installed on the system
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Ensure dependencies are installed
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Ensure repo key is installed
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present

- name: Ensure docker repo is configured
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: present
    filename: docker

- name: Ensure docker in installed
  package:
    name: '{{ docker_package }}'
    state: '{{ docker_package_state }}'

- name: Ensure docker is configured to start on boot
  service:
    name: docker
    enabled: yes
