---
- hosts: default
  become: true
  roles:
    - utilities
    - python3
    - awscli
    - journald-rate-limits
    - flog

    - role: filebeat
      action: install
      version: "{{ filebeat_version }}"

    - role: file_test_server
      action: install

    - role: fluentbit
      action: install
      version: "{{ fluentbit_version }}"

    - role: fluentd
      action: install
      version: "{{ fluentd_version }}"

    - role: http_test_server
      action: install

    - role: logstash
      action: install
      version: "{{ logstash_version }}"

    - role: profiling
      action: install

    - role: splunk_heavy_forwarder
      action: install
      version_with_hash: "{{ splunk_heavy_forwarder_version }}"

    - role: splunk_universal_forwarder
      action: install
      version_with_hash: "{{ splunk_universal_forwarder_version }}"

    - role: tcp_test_server
      action: install

    - role: vector
      action: install
      version: "{{ vector_version }}"
