---
- include_role:
    name: java8

- name: Setup the logstash user
  user:
    name: logstash
    createhome: no
    home: /opt/logstash
    shell: /usr/sbin/nologin

- name: Create the /etc/logstash directory
  file:
    path: /etc/logstash/conf.d
    state: directory

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install ca-certificates
  apt:
    name: ca-certificates
    state: present

- name: Add logstash apt-key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add logstash apt repository
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'
    state: present
    filename: td-agent
    update_cache: yes

- name: Install logstash
  apt:
    name: logstash
    state: present

- name: Install logstash null output plugin
  shell: /usr/share/logstash/bin/logstash-plugin install logstash-output-null
