[sources.in]
  type    = "socket"
  mode    = "tcp"
  address = "0.0.0.0:{{ subject_port }}"

[sinks.out]
  inputs   = ["in"]
  type     = "http"
  uri      = "http://{{ consumer_instance.ec2_private_ip_address }}:{{ consumer_port }}"
  encoding = "ndjson"
  batch_size    = 102400 # 100kib
  batch_timeout = 5 # 5 seconds
