---
- name: Install Vector
  apt:
    deb: "{{ vector_package }}"

# This ensures that the process is not running. Each test is responsible
# for starting and stopping the relevant services.
- name: Ensure the vector service is stopped
  systemd:
    name: vector
    daemon_reload: yes
    enabled: no
    state: stopped
