---
- name: Setup the vector user
  user:
    name: vector
    createhome: no
    home: /opt/vector
    shell: /usr/sbin/nologin

- name: Create the /etc/vector directory
  file:
    path: /etc/vector
    state: directory

- include: "set_config.yml"

- name: "Downloading Vector ({{ version }})"
  get_url:
    url: "http://packages.timber.io/vector/{{ version }}/vector-{{ version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: /tmp/vector.tar.gz
    mode: 0775

- name: Create the /opt/vector/bin directory
  file:
    path: /opt/vector/bin
    state: directory

- name: Create the /var/lib/vector directory
  file:
    path: /var/lib/vector
    state: directory
    owner: vector
    group: vector
    mode: 0770

- name: Unarchive Vector to /opt/vector/bin
  unarchive:
    remote_src: yes
    src: /tmp/vector.tar.gz
    dest: /opt/vector/bin

- name: Remove Vector archive
  file:
    path: /tmp/vector.tar.gz
    state: absent

- name: Install vector daemon systemd script
  copy:
    src: vector.service
    dest: /etc/systemd/system/vector.service
    mode: 0644
    remote_src: no

# This ensures that the process is not running. Each test is responsible
# for starting and stopp the relevant services.
- name: Ensure the vector service is stopped
  systemd:
    name: vector
    daemon_reload: yes
    enabled: no
    state: stopped